(function(){function i(b){this.string=a.textFormat(b).split("\n");this.fontSize=a.config.fontSizeBase;this.height=function(a,b){return this.string.length*this.fontSize*b};this.draw=function(a,b,d,f,g){for(var h=0;h<this.string.length;h++)a.fillText(this.string[h],b+this.fontSize/2*f,d+this.fontSize*h*g)}}var a=a||{},a={config:{},history:{},source:{},main:{},ui:{},init:function(){a.canvas=document.getElementById("vpc");a.ctx=a.canvas.getContext("2d");a.source.init();resources=[new Sprite(0,0,"catgrump.jpg"),
a.source.cg,new Image,new Image,new Image];resources[2].src="catstare.jpg";resources[3].src="catgrump.jpg";resources[4].src="catscreen.png";pl.init(resources.slice(0),a.canvas,function(){setInterval(a.draw,Sprite.Fps25Interval);setInterval(a.update,1);a.advanceSource();a.ui.switchState("text")});a.adjust();window.addEventListener("resize",a.adjust,!1)},advance:function(){a.main.complete()?a.advanceSource():a.main.finish()},advanceSource:function(){this.source.advance()},draw:function(){0<a.config.sW+
a.config.sH&&(a.canvas.width=a.config.sW,a.canvas.height=a.config.sH,a.config.sW=0,a.config.sH=0);a.ctx.clearRect(0,0,a.canvas.width,a.canvas.height);a.main.draw(a.ctx);a.ui.draw(a.ctx)},update:function(){a.main.update()},setText:function(b){a.main.setText(b)},textFormat:function(b){for(var c=b.split(" "),e=10*a.config.wScale*(a.config.wTextBox/a.config.fontSize),d=e,b="",f=0;f<c.length;f++){var g=a.ctx.measureText(c[f]+" ").width;g>d?(d=e-g,b+="\n"):d-=g;b+=c[f]+" "}return b},adjust:function(){var b,
c;"number"==typeof window.innerWidth?(b=window.innerWidth,c=window.innerHeight):document.documentElement&&document.documentElement.clientWidth?(b=document.documentElement.clientWidth,c=document.documentElement.clientHeight):(b=document.body.clientWidth,c=document.body.clientHeight);if(b){b-=a.config.border;c-=a.config.border;b=Math.round(b*a.config.sPercentW);c=Math.round(c*a.config.sPercentH);var e=a.config.sRatioW,d=a.config.sRatioH;b*d!=c*e&&(b*d<c*e?c=d*b/e:b=e*c/d);a.config.sW=b;a.config.sH=
c;a.config.wScale=b/a.config.wDefault;a.config.hScale=c/a.config.hDefault;a.config.fontSize=b/40}},ui:{text:{},menu:{},log:{},state:"text",switchState:function(a){this[this.state].exit();this.state=a;this[this.state].enter()},draw:function(a){this[this.state].draw(a)}}};a.ui.text={draw:function(){},enter:function(){a.main.unfreeze();this.addListeners();a.main.showText()},exit:function(){this.removeListeners()},addListeners:function(){a.canvas.addEventListener("mousedown",this.clickHandle,!1);a.canvas.addEventListener("mousewheel",
this.scrollHandle,!1);a.canvas.addEventListener("DOMMouseScroll",this.scrollHandle,!1);document.body.addEventListener("keydown",this.keyHandle,!1)},removeListeners:function(){a.canvas.removeEventListener("mousedown",this.clickHandle,!1);a.canvas.removeEventListener("mousewheel",this.scrollHandle,!1);a.canvas.removeEventListener("DOMMouseScroll",this.scrollHandle,!1);document.body.removeEventListener("keydown",this.keyHandle,!1)},clickHandle:function(b){switch(b.button){case 0:a.advance();break;case 2:a.ui.switchState("menu")}},
keyHandle:function(b){switch(b.hasOwnProperty("which")?b.which:b.keyCode){case 13:case 39:case 40:a.advance();break;case 37:case 38:a.ui.switchState("log")}},scrollHandle:function(b){b.hasOwnProperty("wheelDelta")?0>b.wheelDelta?a.advance():a.ui.switchState("log"):0<b.detail?a.advance():a.ui.switchState("log")}};a.ui.menu={draw:function(){},enter:function(){a.main.freeze();a.main.hideText();this.addListeners()},exit:function(){this.removeListeners()},addListeners:function(){a.canvas.addEventListener("mousedown",
this.clickHandle,!1)},removeListeners:function(){a.canvas.removeEventListener("mousedown",this.clickHandle,!1)},clickHandle:function(){a.ui.switchState("text")}};a.ui.log={draw:function(b){a.history.draw(b)},enter:function(){a.main.freeze();a.main.hideText();this.addListeners()},exit:function(){this.removeListeners()},addListeners:function(){a.canvas.addEventListener("mousedown",this.clickHandle,!1);a.canvas.addEventListener("mousewheel",this.scrollHandle,!1);a.canvas.addEventListener("DOMMouseScroll",
this.scrollHandle,!1);document.body.addEventListener("keydown",this.keyHandle,!1)},removeListeners:function(){a.canvas.removeEventListener("mousedown",this.clickHandle,!1);a.canvas.removeEventListener("mousewheel",this.scrollHandle,!1);a.canvas.removeEventListener("DOMMouseScroll",this.scrollHandle,!1);document.body.removeEventListener("keydown",this.keyHandle,!1)},clickHandle:function(b){switch(b.button){case 0:a.ui.switchState("text");break;case 2:a.ui.switchState("menu")}},keyHandle:function(b){switch(b.hasOwnProperty("which")?
b.which:b.keyCode){case 13:case 39:case 37:a.ui.switchState("text");break;case 38:a.history.scrollUp();break;case 40:a.history.scrollDown()}},scrollHandle:function(b){b.hasOwnProperty("wheelDelta")?0>b.wheelDelta?a.history.scrollDown():a.history.scrollUp():0<b.detail?a.history.scrollDown():a.history.scrollUp()}};a.source={init:function(){this.catIndex=0;this.cats=[];this.catsText=[];this.cg=new Sprite(400,100,"sprite0_strip100.png",0,0,85,70);this.cats[0]=[new Sprite(0,0,"catgrump.jpg"),this.cg];
this.cats[1]=[new Sprite(0,0,"catsit.gif"),new Sprite(400,100,"catscreen.png"),this.cg];this.cats[2]=[new Sprite(0,0,"catsit.gif"),new Sprite(400,100,"catscreen.png"),this.cg];this.cats[3]=[new Sprite(0,0,"catsit.gif"),new Sprite(400,100,"catscreen.png"),this.cg];this.cats[4]=[new Sprite(0,0,"catgrump.jpg"),this.cg];this.cats[5]=[new Sprite(0,0,"catside.jpg"),new Sprite(50,50,"catstare.jpg"),this.cg];this.cats[6]=[new Sprite(50,50,"catstare.jpg"),new Sprite(0,0,"catside.jpg"),this.cg];this.cats[7]=
[this.cg];for(var a="{0 ",c=1;100>c;c+=2)this.cg.addFrame(85*c,0,85,70),a+=c+" ";this.cg.newAnimation("spin",a+"}");this.cg.newAnimation("twitch","{0 1 2 3 4 5 6 7 8 9 10 9 8 7 6 5 4 3 2 1}r");this.cg.play("twitch");this.catsText[0]="Grumpy Cat: Miau!  Mi-miau-miau-miau miaau miaaau miau miau.";this.catsText[1]="Left Cat: Nyan.  Nya-nya-nyaaa nya-nya nya.";this.catsText[2]="Cat on Telecommunicator: Mew mew mewmewmew.  Mewmew meew meeew meeeew.";this.catsText[3]="Left Cat: Nyanfred.  Nyan nya nyan nyanyans nyan-nya nyan.";
this.catsText[4]="Grumpy Cat: MIAU MIAU!";this.catsText[5]="Stacked Cat I:Meeeeow.  Mew meow meow meeeeow.";this.catsText[6]="Stacked Cat II: Maow.  Maow maaaow maaaow maow maow. Maow maowmaowmaow maow maow maow-maow maow maowmaowowow. Mao maow, maow mao!";this.catsText[7]="And so it begins..."},advance:function(){a.history.addEntry(new i(this.catsText[this.catIndex]));a.setText(this.catsText[this.catIndex]);a.main.clear();a.main.addImages(this.cats[this.catIndex++],0);this.catIndex==this.cats.length&&
(this.catIndex=0)}};a.main={images:{},frozen:!1,frozenImg:{},frozenCtx:{},text:{},draw:function(b){var c=a.config.hScale,e=a.config.wScale;if(this.frozen)b.drawImage(this.frozenImg,0,0,this.frozenImg.width*e,this.frozenImg.height*c);else for(var d=0;d<this.images.length();d++){var f=this.images.get(d);f.draw?f.draw(b,e,c):f.width&&b.drawImage(f,0,0,f.width*e,f.height*c)}this.text.draw(b)},freeze:function(){if(!this.frozen){this.frozenImg.tagName&&"CANVAS"==this.frozenImg.tagName.toUpperCase()||(this.frozenImg=
document.createElement("canvas"),this.frozenCtx=this.frozenImg.getContext("2d"));this.frozenImg.width=a.config.wDefault;this.frozenImg.height=a.config.hDefault;for(var b=0;b<this.images.length();b++){var c=this.images.get(b);c.draw?c.draw(this.frozenCtx,1,1):c.width&&this.frozenCtx.drawImage(c,0,0,c.width,c.height)}this.frozen=!0;this.text.frozen=!0}},unfreeze:function(){this.frozen=!1;this.text.frozen=!1},showText:function(){this.text.visible=!0},hideText:function(){this.text.visible=!1},setText:function(a){this.text.set(a)},
clear:function(){this.images.clear()},update:function(){this.text.update()},complete:function(){return this.text.complete()},finish:function(){this.text.finish()},addImage:function(a,c){this.images.addImage(a,c);this.images.sort()},addImages:function(a,c){for(var e=1;e<a.length;)e*=10;for(var d=0;d<a.length;d++)this.images.addImage(a[d],c+d/e);this.images.sort()}};a.main.images={images:[],clear:function(){this.images.splice(0,this.images.length)},get:function(a){return this.images[a].image},length:function(){return this.images.length},
addImage:function(a,c){this.images.push({image:a,d:c})},sort:function(){this.images.sort(function(a,c){return a.d-c.d})}};a.main.text={clock:0,index:0,display:"",pallet:"",frozen:!1,visible:!0,draw:function(b){if(this.visible){b.save();var c=a.config,e=(c.wDefault-c.wTextBox)/2,d=c.hDefault-c.hTextBox-e;b.fillStyle=c.cTextBox;b.fillRect(e*c.wScale,d*c.hScale,c.wTextBox*c.wScale,c.hTextBox*c.hScale);c.setFont(b);for(var f=this.display.split("\n"),g=0;g<f.length;g++)b.fillText(f[g],(e+c.fontSizeBase/
2)*c.wScale,(d+c.fontSizeBase*(g+0.25))*c.hScale);b.restore()}},update:function(){!this.frozen&&!this.complete()&&(-1==a.config.textSpeed?this.display=this.pallet:0==this.clock--&&(this.clock=a.config.textSpeed,this.display+=this.pallet.charAt(this.index++)))},complete:function(){return this.pallet.length<=this.display.length},reset:function(){this.index=this.clock=0;this.display=""},finish:function(){this.display=this.pallet},set:function(b){this.reset();this.pallet=a.textFormat(b)}};a.history={entries:[],
logCanvas:{},logContext:{},position:0,addEntry:function(b){this.entries.push(b);this.entries.length>a.config.historySize&&this.entries.splice(0,1)},draw:function(b){var c,e,d=a.config;e=(d.wDefault-d.wHistory)/2;c=(d.hDefault-d.hHistory)/2;this.logCanvas.tagName&&"CANVAS"==this.logCanvas.tagName.toUpperCase()||(this.logCanvas=document.createElement("canvas"),this.logContext=this.logCanvas.getContext("2d"));this.logCanvas.width=d.wHistory*d.wScale;this.logCanvas.height=d.hHistory*d.hScale;this.logContext.fillStyle=
d.cTextBox;this.logContext.fillRect(0,0,d.wHistory*d.wScale,d.hHistory*d.hScale);d.setFont(this.logContext);this.logContext.textBaseline="bottom";for(var f=this.entries.length-this.position-1,g=this.logCanvas.height;0<=f&&0<g;){var h=this.entries[f],g=g-h.height(this.logContext,d.hScale);h.draw(this.logContext,0,g,d.wScale,d.hScale);g-=d.historyGap*d.hScale;f--}b.drawImage(this.logCanvas,e,c,this.logCanvas.width,this.logCanvas.height)},scrollUp:function(a){!isNaN(parseFloat(a))&&(isFinite(a)&&1<a)&&
this.scrollUp(--a);this.position<this.entries.length-1&&this.position++},scrollDown:function(a){!isNaN(parseFloat(a))&&(isFinite(a)&&1<a)&&this.scrollDown(--a);0!=this.position&&this.position--}};a.config={sPercentW:1,sPercentH:1,sRatioW:4,sRatioH:3,border:15,wDefault:800,hDefault:600,wTextBox:750,hTextBox:175,wHistory:750,hHistory:550,historySize:60,historyGap:25,sW:this.wDefault,sH:this.hDefault,wScale:1,hScale:1,fontType:"PTSansRegular",cText:"rgba(255,255,255,1)",cTextBox:"rgba(0,0,0,.4)",textSpeed:1,
fontSizeBase:20,fontSize:this.fontSizeBase,setFont:function(a){a.shadowOffsetX=-2;a.shadowOffsetY=2;a.shadowBlur=2;a.shadowColor="rgba(0, 0, 0, 0.5)";a.font=this.fontSize+"px "+this.fontType;a.fillStyle=this.cText;a.textBaseline="top"}};a.init()})();
